### PR TITLE
Enable the stricter runtime sanitization checks with `-DDEBUG`

### PR DESCRIPTION
**Pull request by DaveDuck321**
The `hashFunctions` unit-tests failed when the extra runtime sanitation was enabled. This PR fixes the issue and enables the stricter checks in debug mode.

@ChasingNeutrons does this look reasonable?

### CODE REVIEW

**Comment by Mikolaj-A-Kowalski** [comment]
Thanks for the PR! I think it is ready to go! 
The only question I have is which versions of the gfortran were you able to run it with? I just vaguely remember that I did not enable all the checks back in the day, because they used to be a big buggy and there were some false positives.

**Review by Mikolaj-A-Kowalski — APPROVED** [review]

**Comment by DaveDuck321** [comment]
I'm using `GNU Fortran (GCC) 12.2.0`, there haven't been any false positives in the unit-tests or input files I've tried. If everyone else is using an older version maybe that should be tested too?

There is now an extra runtime warning about temporary array creation in the `uniFills` test but I've kept this on since this should probably be avoided in new code.

**Comment by Mikolaj-A-Kowalski** [comment]
I have checked with the older GFortran compilers (7,8,9) and it seems that the 7.5 results in the buggy warnings. 

If you are all right with it I would just add a comment in CMake where the debug flags are set to highlight that it may not work correctly with GFortran 7.5.  Anyway, I think that GFortran 7.5 is lost to us as soon we will have to switch to pfUnit in version 4.0 (see #10 ) so it is not a problem. 

I can do it myself if you prefer. Otherwise I think it is ready to merge unless there is anything you wish to add? 

Once again thank you for the fix!

**Comment by DaveDuck321** [comment]
> I can do it myself if you prefer. Otherwise I think it is ready to merge unless there is anything you wish to add?

Cool, thanks. I've added the comment you suggested.

This PR should be good to merge as a standalone change, I'm not planning to add anything else regarding the tooling.

**Pull request merged**
